BW.Presenter.Layer/BW.WebsiteApp/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BW.Website.Common.Helpers;
using BW.Data.Contract.DTOs;
using BW.Website.Common.Utilities;
using BW.Common.Consts;

namespace BW.WebsiteApp.Controllers
{
    public class RoleController : Controller
    {
        // GET: Users
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult Index()
        {
            var getAllRoleMore = RoleHelper.GetAllRoleMoreInfo().Data;
            return View(getAllRoleMore);
        }

        // GET: Users/Details/5
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult Details(string roleId)
        {
            var result = RoleHelper.GetRoleById(roleId).Data;
            return View(result);
        }

        // GET: Users/Create
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult Create(RoleCreateView roleCreateView)
        {
            if (ModelState.IsValid)
            {
                var result = RoleHelper.InsertRole(roleCreateView);
                if (result.Data)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(roleCreateView);
        }

        // GET: Users/Edit/5
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult Edit(string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = RoleHelper.GetRoleById(roleId).Data;
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult Edit(RoleView roleView)
        {
            if (ModelState.IsValid)
            {
                var result = RoleHelper.UpdateRole(roleView).Data;
                if (result)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(roleView);
        }

         //GET: Users/Delete/5
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult Delete(string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = RoleHelper.GetRoleById(roleId).Data;
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult DeleteConfirmed(string roleId)
        {
            RoleHelper.DeleteRole(roleId);
            return RedirectToAction("Index");
        }
    }
}

BW.Presenter.Layer/BW.WebsiteApp/Controllers/RoleInPermissionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BW.Website.Common.Helpers;
using BW.Data.Contract.DTOs;
using BW.Website.Common.Utilities;
using BW.Common.Consts;

namespace BW.WebsiteApp.Controllers
{
    public class RoleInPermissionController : Controller
    {
        // GET: RoleInPermission
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ShowData(string roleIdEnc)
        {
            var result = RoleInPermissionHelper.GetRoleInPermissionByRoleId(roleIdEnc).Data;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_PermissionsPartialView", result);
            }
            else
            {
                return View();
            }
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        [AuthorizedUser(PermissionCodes.AllowAnonymous)]
        public bool SaveChange(List<RoleInPermissonView> data)
        {
            var result = RoleInPermissionHelper.UpdateRoleInPermission(data).Data;
            return result;
        }
    }
}

BW.Presenter.Layer/BW.WebsiteApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BW.Website.Common.Helpers;
using BW.Data.Contract.DTOs;
using BW.Website.Common.Utilities;
using BW.Common.Consts;
using PagedList;
using BW.Website.Resource;



namespace BW.WebsiteApp.Controllers
{
    public class UserController : Controller
    {
        [AuthorizedUser(PermissionCodes.ViewManageUser)]
        public ActionResult Index(int? page)
        {
            log4net.ILog logger = log4net.LogManager.GetLogger(typeof(UserController));
            logger.Info("test12345");
            var getAllUser = UserHelper.GetAllUser().Data;
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(getAllUser.ToPagedList(pageNumber, pageSize));
        }

        // GET: Users/Details/5
        [AuthorizedUser(PermissionCodes.ViewManageUser)]
        public ActionResult Details(string userId)
        {
            //var result = UserHelper.GetUserById(ApiServiceUtilities.Encrypt(userId)).Data;
            var result = UserHelper.GetUserById(userId).Data;
            return View(result);
        }

        // GET: Users/Details/5
        [AuthorizedUser(PermissionCodes.ViewManageUser)]
        public ActionResult ViewProfile()
        {
            string userIdEnc = AuthorizationHelper.UserId.ToString();
            var result = UserHelper.GetUserById(ApiServiceUtilities.Encrypt(userIdEnc)).Data;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_UserProfilePartialView", result);
            }
            else
            {
                return View();
            }
        }

        // GET: Users/Create
        [AuthorizedUser(PermissionCodes.AddManageUser)]
        public ActionResult Create()
        {
            UserCreateView dto = new UserCreateView();
            dto.roles = RoleHelper.GetRoleActive().Data;
            return View(dto);
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizedUser(PermissionCodes.AddManageUser)]
        public ActionResult Create(UserCreateView userCreateView, string[] groupRole)
        {
            //Validate with javascript is disabled
            //if (UserHelper.CheckUnitEmail(userCreateView.Email).Data)
            //{
            //    ModelState.AddModelError("Email", GlobalResource.validEmailIsExit);
            //}

            if (ModelState.IsValid)
            {
                var result = UserHelper.InsertUser(userCreateView, groupRole);
                if (result.Data)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(userCreateView);
        }

        // GET: Users/Edit/5
        [AuthorizedUser(PermissionCodes.EditManageUser)]
        public ActionResult Edit(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = UserHelper.GetUserById(userId).Data;
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        [HttpPost]
        [AuthorizedUser(PermissionCodes.EditManageUser)]
        public ActionResult Edit(UserView userView, string[] groupRole)
        {
            if (ModelState.IsValid)
            {
                var result = UserHelper.UpdateUser(userView, groupRole);
                if (result.Data)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(userView);
        }

        // GET: Users/EditProfile/5
        [AuthorizedUser(PermissionCodes.EditManageUser)]
        public ActionResult EditProfile()
        {
            string userIdEnc = AuthorizationHelper.UserId.ToString();
            var result = UserHelper.GetUserById(ApiServiceUtilities.Encrypt(userIdEnc)).Data;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_EditProfilePartialView", result);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        [AuthorizedUser(PermissionCodes.EditManageUser)]
        public string EditProfile(UserProfileView userProfileView)
        {
            if (ModelState.IsValid)
            {
                var result = UserHelper.EditProfile(userProfileView);
                if (result.Data)
                {
                    return "Update successful!";
                }
            }

            return "Update fail!";
        }

        [AuthorizedUser(PermissionCodes.DeleteManageUser)]
        public ActionResult Delete(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = UserHelper.GetUserById(userId).Data;
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [AuthorizedUser(PermissionCodes.DeleteManageUser)]
        public ActionResult DeleteConfirmed(string userId)
        {
            UserHelper.DeleteUser(userId);
            return RedirectToAction("Index");
        }

        [AuthorizedUser(PermissionCodes.EditManageUser)]
        public ActionResult UpdatePassword()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("_UpdatePasswordPartialView");
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public string UpdatePassword(UserPasswordView userPassView)
        {
            //check old password
            string userIdEnc = AuthorizationHelper.UserId.ToString();
            var user = UserHelper.GetUserById(ApiServiceUtilities.Encrypt(userIdEnc)).Data;
            if (!UserHelper.CheckOldPassword(user.Email, ApiServiceUtilities.MD5Hash(userPassView.OldPassword)))
            {
                return "Wrong current password!";
            }else
            {
                UserHelper.UpdatePassword(userPassView);
                return "Change password success!";
            }

        }
        public JsonResult IsEmailExits(string email)
        {
            return Json(!UserHelper.CheckUnitEmail(email).Data, JsonRequestBehavior.AllowGet);
        }
    }
}

BW.Presenter.Layer/BW.WebsiteApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    @using BW.Website.Common.Constants
    @using BW.Website.Common.Helpers;
    @using BW.Common.Consts;
    @{
        var isViewManageUser = AuthorizationHelper.HasPermissionFor(PermissionCodes.ViewManageUser);

        var isViewManageRole = AuthorizationHelper.HasPermissionFor(PermissionCodes.ViewManageRole);

        var isViewRoleInPermission = AuthorizationHelper.HasPermissionFor(PermissionCodes.ViewRoleInPermission);
    }
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Better Work", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (isViewManageUser)
                    {
                        <li class="@(ViewBag.System == ConstSharing.userIndex ? "active" : "")">
                            @Html.ActionLink("User Management", "Index", "User")
                        </li>
                    }
                    @if (isViewManageRole)
                    {
                        <li class="@(ViewBag.System == ConstSharing.roleIndex ? "active" : "")">
                            @Html.ActionLink("Role Management", "Index", "Role")
                        </li>
                    }
                    @if (isViewRoleInPermission)
                    {
                        <li class="@(ViewBag.System == ConstSharing.roleInPerm ? "active" : "")">
                            @Html.ActionLink("Role In Permission", "Index", "RoleInPermission")
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>

BW.Presenter.Layer/BW.WebsiteApp/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>